### PR TITLE
Updating cacert.txt

### PR DESCRIPTION
**Pull request by Rusox89**
Adding Go Daddy Root Certificate Authority - G2 to the bundle

### CODE REVIEW

**Comment by temoto** [comment]
@Rusox89 hello, thanks for patch.

Please describe why it should be included.
Please add same modification to python3/httplib2/cacerts.txt

**Comment by Rusox89** [comment]
Hello @temoto, thanks for your swift reply,

We are using httplib2 indirectly in our projects and we just bought a certificate from Godaddy, which is recognized by the browser but not by any python library like `requests`, `httplib2`, not even `curl` binary, we found out this is a intermediate certificate, which seems to be the issuer of our new certificate, so we solve it by adding the missing intermediate to each machine we deploy. We though we could solve this once and for all by adding it directly to the repo, and so if anyone else is has a certificate issued by this one being added, it will not complain. I have tried to add the same certificate to the `certifi` project, but they use the Mozilla Store to extract only ROOT certificates, which means that `requests` will not be able to verify any certificate issued by a these intermediates although they have a extensive list of intermediate certs which get shipped with the browser

**Comment by temoto** [comment]
Thanks for info. Pass by browser is a good landmark for me. I'll have to check few things because it's important security question. Feel free to ping if you think it's getting forgotten.

**Comment by temoto** [comment]
@Rusox89 sorry for big delay in response.

As of now I don't see better trust source than Mozilla CA list distributed as `certifi` python package to feed our cacerts.txt

You can still add required CA in your project, just add path where you initialize httplib.Http object, like so:

`http = httplib2.Http(ca_certs='/path/to/custom/cacerts.txt')`

In future we will probably have `certifi` as dependency to avoid maintaining trusted CA file.

**Pull request closed without merging**
