### PR TITLE
Fixed formatting of headers

### PR DESCRIPTION
**Pull request by ocelotluke**
Some of the headers didn't have the correct spacing.

### CODE REVIEW

**Comment by cdent** [comment]
@ocelotluke why did you close?

**Comment by ocelotluke** [comment]
Because I don't know what I'm doing when it comes to pull requests. What is the process from here?

**Comment by cdent** [comment]
Everything is okay. At this stage there's nothing left for you to do. Someone else will likely review this and then merge it. It's a very useful contribution, thanks very much.

**Comment by ocelotluke** [comment]
Don't know about that, thanks for clarifying.

**Comment by FND** [comment]
_/me appreciates this kinda attention to detail_

Thank you, @ocelotluke.

**Pull request merged**
