### PR TITLE
ssl: hostname mismatch was checked only once (python2 fix)

### PR DESCRIPTION
**Pull request by temoto**
https://github.com/httplib2/httplib2/issues/5
https://github.com/jcgregorio/httplib2/issues/243

Code review and/or live testing are very valuable.

This fix is the last release blocker for v0.10.

### CODE REVIEW

**Comment by temoto** [comment]
Please ignore Travis failures for now.

**Comment by sigmavirus24** [comment]
Is there a reason not to do this for Python 3 as well?

**Comment by temoto** [comment]
So far I could not reproduce the error in test. I trust this is required
for Python 2, maybe on 3 there is no such issue. Feedback is much
appreciated.

**Comment by temoto** [comment]
This patch was included in v0.10.1 release, already on PyPI.

**Pull request closed without merging**
