### PR TITLE
Get CA_CERTS path from other sources

### PR DESCRIPTION
**Pull request by ryansmith940**
Get the CA_CERTS path from certifi if available, or from the environment variable HTTPLIB2_CA_CERTS, if available.  Default to the bundled cacerts file.

### CODE REVIEW

**Comment by galvez** [comment]
@httplib2/maintainers Any objection to merging this? LGTM

**Comment by stinky2nine** [comment]
@ryansmith940 Can you add test coverage?

**Comment by dirkboye** [comment]
friendly ping. I could use that option to load custom file by environment variable

**Comment by temoto** [comment]
Variant of this patch has been merged.

**Pull request closed without merging**
