### PR TITLE
Add python3 proxy support

### PR DESCRIPTION
**Pull request by prouhard**
Fix:
- https://github.com/httplib2/httplib2/issues/53
- https://github.com/httplib2/httplib2/issues/25
- https://github.com/httplib2/httplib2/issues/22

\+ some automatic code refacto

### CODE REVIEW

**Comment by temoto** [comment]
@Reupiey hello. Thanks a lot for your contribution!

Could you remove automatic code style changes? Without tests this is too much to read.

**Comment by Reupiey** [comment]
@temoto Hi !
I will probably have some time tomorrow morning to look into that :)

**Comment by cveilleux** [comment]
@temoto I removed the automatic code style changes from this PR and made a cleaned-up version. Please see #90

**Comment by temoto** [comment]
Another version of this work has been merged into master.

**Pull request closed without merging**
