### PR TITLE
parse auth headers using pyparsing instead of regexp

### PR DESCRIPTION
**Pull request by temoto**
Fixes CPU burn DoS by cubic complexity of whitespace matching in
WWW_AUTH_RELAXED (default) regexp.

### CODE REVIEW

**Comment by temoto** [comment]
@b-c-ds please take a look too, I can't add you to reviewers.

**Comment by temoto** [comment]
minor update in script/release to read `__version__` in source without installing pyparsing

**Comment by b-c-ds** [comment]
@temoto I'd never heard of the pyparsing module before... seems like a great alternative to regex. Looks good to me. 👍

**Comment by b-c-ds** [comment]
Hello, do you know when you are planning to merge this?

**Comment by temoto** [comment]
@b-c-ds hey, thanks for reminder, I was waiting for more reviews. This fix is released in 0.19.0.

**Pull request merged**
