### PR TITLE
Fix parsing http_proxy environment.

### PR DESCRIPTION
**Pull request by kramarz**
Parsing proxy was breaking when proxy URL was set to ipv6 address. There
was also weird handling of proxy without a password. We should rely on
parsing those fields in urllib which is present in all supported
versions.

### CODE REVIEW

**Comment by temoto** [comment]
Thank you. It's nice and clean now. This is exactly what would merge #206.

Can get rid of single use variables now.

```python
    url = urlparse.urlparse(url)

    proxy_type = 3  # socks.PROXY_TYPE_HTTP
    pi = ProxyInfo(
        proxy_type=proxy_type,
        proxy_host=url.hostname,
        proxy_port=url.port or dict(https=443, http=80)[method],
        proxy_user=url.username or None,
        proxy_pass=url.password or None,
        proxy_headers=None,
    )
```

If you agree, i can apply it myself.

**Comment by temoto** [comment]
flake8: tests/test_proxy.py:49:1: E302 expected 2 blank lines, found 1

**Comment by kramarz** [comment]
Thanks. I have amended these fixes.

**Comment by temoto** [comment]
@kramarz thank you very much, released in 0.20.4

**Pull request merged**
