### PR TITLE
Respect NO_PROXY env var in proxy_info_from_url().

### PR DESCRIPTION
**Pull request by houglum**
This allows users to specify an override value for the noproxy list, in
addition to overriding the proxy url, in proxy_info_from_url(). If no
override is given, we should respect the values in the no_proxy/NO_PROXY
environment variables, if present. This behavior can be seen in other
tools like curl (see curl/curl#1140).

I would also tweak this for the python3 module, but its ProxyInfo class
doesn't even seem to have a bypass_hosts attribute.

### CODE REVIEW

**Comment by houglum** [comment]
Also, FYI, this was intended to address GoogleCloudPlatform/gsutil#435.

**Comment by houglum** [comment]
**Friendly ping** :)

**Comment by temoto** [comment]
LGTM

**Comment by temoto** [comment]
@houglum thanks for reminder.

**Comment by houglum** [comment]
Looks like this is approved - is there anything else I need to do to get it merged?

**Comment by temoto** [comment]
We'll wait for at least one more review for a week and then merge anyway.

**Comment by temoto** [comment]
@httplib2/maintainers ping

**Pull request merged**
