### PR TITLE
Add major.minor classifiers

### PR DESCRIPTION
**Pull request by hugovk**
Assuming 2.5+ from https://github.com/httplib2/httplib2/pull/76.

### CODE REVIEW

**Comment by temoto** [comment]
Does it help for something?

**Comment by hugovk** [comment]
Yes, it allows scripts and other tools determine what versions of Python a package supports. It's also a clear way of telling your users (robotic and human) what versions are supported.

**Comment by temoto** [comment]
I don't mean the theoretical idea of version classifiers. I mean this particular patch listing all minor versions, is there a real world use of it?

**Comment by hugovk** [comment]
Yes, [this tool](https://hugovk.github.io/drop-python/3.2/) looks for packages which are still using old versions of Python to try help update them and [move things forward](https://snarky.ca/stop-using-python-2-6/).

**Comment by temoto** [comment]
Basically, you want to add all minor versions so that your tool will
suggest removing some of them. That's convoluted. Wait for 2/3 code base
merge, it will clear minor versions support as a side effect.

On linked tool: We'll drop support for older pythons because it will gain
benefits for users, not because other libraries or pypi traffic. That's
ridiculous arguments.

Please write about helpful use cases for this patch if you know any.

**Comment by hugovk** [comment]
As an end user, I would like to know what versions of Python are supported by this library.

It is not documented anywhere. The classifiers are a well-known and well-used standard, used by over 75% of the most-downloaded Python packages.

**Comment by stinky2nine** [comment]
LGTM

**Comment by temoto** [comment]
Merged in 10909e980477578f909b1e164476d9149ff3581e

Thank you @hugovk

**Pull request closed without merging**
