### PR TITLE
proxy: no_proxy=bar was matching foobar

### PR DESCRIPTION
**Pull request by temoto**
https://github.com/httplib2/httplib2/issues/94

@cveilleux review please

### CODE REVIEW

**Comment by cveilleux** [comment]
@temoto The change is OK and fixes the domain prefix bug.

But, the change seems to always include subdomains automatically. That is not how curl and wget work for example.

Source:

## curl

```
        NO_PROXY
 
  If the host name matches one of these strings, or the host is within the
  domain of one of these strings, transactions with that node will not be
  proxied. When a domain is used, it needs to start with a period. A user can
  specify that both www.example.com and foo.example.com should not uses a
  proxy by setting NO_PROXY to ".example.com". By including the full name you
  can exclude specific host names, so to make www.example.com not use a proxy
  but still have foo.example.com do it, set NO_PROXY to "www.example.com"
```
https://curl.haxx.se/docs/manual.html

## wget

```
no_proxy
This variable should contain a comma-separated list of domain
extensions proxy should not be used for.
For instance, if the value of no_proxy is ‘.mit.edu’, proxy
will not be used to retrieve documents from MIT.
```
https://www.gnu.org/software/wget/manual/wget.html


There is no official standard for the no_proxy env var... best solution is probably to copy what other major software and libs are doing...

**Comment by temoto** [comment]
Ironically, I got the always-match subdomains behavior from curl issue you linked. https://github.com/curl/curl/issues/1208#issuecomment-272837735

> The value can specify subdomains in presence or absence of the dot (e.g. .example.com or example.com) but can not specify regular expression (e.g. *.example.com).

**Comment by temoto** [comment]
@cveilleux fixed

**Comment by cveilleux** [comment]
Yes, sorry for the confusing reference I posted in #94. The man page is clearer.

The change LGTM.

**Comment by stinky2nine** [comment]
LGTM

**Comment by temoto** [comment]
Never mind pull request status, Github is wrong, fix was merged.

**Pull request closed without merging**
